# Use postgres/example user/password credentials
#user: postgres
#pass: example
version: '3.1'

services:

  db:
    image: postgres
    #restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./postgres_data:/var/lib/postgresql

  adminer:
    image: adminer
    #restart: always
    ports:
      - 8080:8080

